### ISSUE TITLE
Have to click the To-do List "x" multiple times to clear all completed To-do's

### ISSUE THREAD

**Issue by akkota** [narlock/OpenLife#7]
https://user-images.githubusercontent.com/108426332/232667593-341be78a-3bf0-4db0-a94c-f6de8bd24598.mov

Hey, here's a video of what's happening. I'm not sure if the button intends to clear all to-do's at once but as you can see I have to click it multiple times to get all my To-do's cleared.

**Comment by narlock** [comment]
https://user-images.githubusercontent.com/59890724/233111805-9fc3af46-72e5-400c-9ea6-65681887b7f9.mov

should be g2g for next release
