### ISSUE TITLE
Todo List "Copy to clipboard" doesn't copy the entire list

### ISSUE THREAD

**Issue by akkota** [narlock/OpenLife#8]
https://user-images.githubusercontent.com/108426332/233356430-5d7e23a8-8b32-4605-a97c-c5395c52694c.mp4

All my tasks aren't copied when I do copy to clipboard.

**Comment by narlock** [comment]
Hey, I believe the current implementation only supports 9 tasks to be on the copy to clipboard function. This is not a bug, but could eventually expand to an enhancement.

Feel free to reopen this issue if there are other related issues you find like this! I really appreciate it.

https://github.com/narlock/Kaizen/blob/main/KaizenClient/src/state/TodoState.java#L388
